language: c
script: make -C vmc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libc6-i386
    - libc6-dev-i386
    - linux-libc-dev:i386
    - libfl-dev:i386
    - gcc-multilib
    - bison
